name = "CompositeTypes"
uuid = "b152e2b5-7a66-4b01-a709-34e65c35f657"
authors = ["Daan Huybrechs <daan.huybrechs@kuleuven.be>"]
version = "0.1.2"

[deps]

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
